# Generated by Django 2.2.4 on 2019-12-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('idno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('contact', models.IntegerField(unique=True)),
                ('image', models.ImageField(upload_to='AdminImage/')),
            ],
        ),
    ]
