# Generated by Django 2.2.4 on 2019-12-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('contact', models.IntegerField(unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='userImage/')),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
