# Generated by Django 2.2.4 on 2019-12-17 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=30)),
                ('minprice', models.FloatField()),
                ('discription', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='productImage/')),
                ('userinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.UserModel')),
            ],
        ),
        migrations.CreateModel(
            name='MaxAmountModel',
            fields=[
                ('maid', models.AutoField(primary_key=True, serialize=False)),
                ('maxamount', models.FloatField()),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.ProductModel')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.UserModel')),
            ],
        ),
        migrations.CreateModel(
            name='BiddingModel',
            fields=[
                ('bidid', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.ProductModel')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.UserModel')),
            ],
        ),
    ]
